#!/usr/bin/env python3
"""
Plot the MMS convergence curve for DG + TVDRK2.

Reads CSV output files generated by run_mms.py and produces a log-log plot
of element size h vs. L2 error, with a reference O(h²) line.

Usage:
    python plot_convergence.py                  # auto-find CSVs from run_mms.py output
    python plot_convergence.py --h 0.02 0.01 0.005 --err 1e-3 2.5e-4 6.25e-5  # manual input
"""

import sys
import csv
from pathlib import Path
import argparse

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

SCRIPT_DIR = Path(__file__).resolve().parent

# ── Data loading ───────────────────────────────────────────────────────────

def load_from_csvs(nx_list=(50, 100, 200)):
    """Read L2 error from CSV files generated by run_mms.py."""
    h_vals, err_vals = [], []
    for nx in nx_list:
        csv_path = SCRIPT_DIR / f"mms_out_n{nx}.csv"
        if not csv_path.exists():
            print(f"WARNING: {csv_path} not found, skipping nx={nx}")
            continue
        with open(csv_path, "r") as f:
            rows = list(csv.DictReader(f))
        if not rows:
            continue
        last = rows[-1]
        h = 1.0 / nx              # true dx for pseudo-1D mesh
        err = float(last["l2_error"])
        h_vals.append(h)
        err_vals.append(err)
        print(f"  nx={nx}: h={h:.6f}, L2_error={err:.6e}")
    return np.array(h_vals), np.array(err_vals)


# ── Plotting ───────────────────────────────────────────────────────────────

def plot_convergence(h, err, out_path=None):
    """Generate a log-log convergence plot with O(h²) reference line."""
    # Fit slope
    log_h = np.log(h)
    log_err = np.log(err)
    slope, intercept = np.polyfit(log_h, log_err, 1)

    # Reference O(h²) line — passes through the finest-mesh point
    ref_h = np.array([h[0] * 1.3, h[-1] * 0.7])
    ref_err = err[-1] * (ref_h / h[-1]) ** 2

    fig, ax = plt.subplots(figsize=(6, 5))

    # Data points
    ax.loglog(h, err, "ko", markersize=8, markerfacecolor="k", label="DG + TVDRK2")
    # Best-fit line
    ax.loglog(h, np.exp(intercept) * h ** slope, "k--", linewidth=1,
              label=f"Best fit: slope = {slope:.2f}")
    # O(h²) reference
    ax.loglog(ref_h, ref_err, "gray", linewidth=1, linestyle="dotted",
              label=r"$\mathcal{O}(h^2)$ reference")

    ax.set_xlabel("Element size  $h$", fontsize=12)
    ax.set_ylabel(r"$L_2$ error  $\|\rho^h - \rho_{\mathrm{exact}}\|_{L_2}$", fontsize=12)
    ax.set_title("MMS Convergence: 1D Transport  (DG + TVDRK2)", fontsize=13)
    ax.legend(fontsize=10, loc="lower right")
    ax.grid(True, which="both", linestyle=":", alpha=0.5)

    # Annotate data points with (h, error)
    for hi, ei in zip(h, err):
        ax.annotate(f"h={hi:.3f}\nerr={ei:.2e}",
                    xy=(hi, ei), xytext=(8, 8), textcoords="offset points",
                    fontsize=8, alpha=0.7)

    fig.tight_layout()
    out = out_path or str(SCRIPT_DIR / "mms_convergence.png")
    fig.savefig(out, dpi=150)
    print(f"\nPlot saved to: {out}")
    plt.show()


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Plot MMS convergence curve")
    parser.add_argument("--h", type=float, nargs="+",
                        help="Element sizes (manual input)")
    parser.add_argument("--err", type=float, nargs="+",
                        help="L2 errors (manual input, same order as --h)")
    parser.add_argument("--nx", type=int, nargs="+", default=[50, 100, 200],
                        help="Mesh sizes to look for (default: 50 100 200)")
    parser.add_argument("-o", "--output", type=str, default=None,
                        help="Output image path")
    args = parser.parse_args()

    if args.h and args.err:
        if len(args.h) != len(args.err):
            print("Error: --h and --err must have the same number of values.")
            sys.exit(1)
        h = np.array(args.h)
        err = np.array(args.err)
    else:
        h, err = load_from_csvs(args.nx)
        if len(h) < 2:
            print("Error: need at least 2 data points. Run run_mms.py first, "
                  "or provide manual data with --h and --err.")
            sys.exit(1)

    plot_convergence(h, err, args.output)


if __name__ == "__main__":
    main()
