#!/usr/bin/env python3
"""
Publication-quality MMS convergence plot for DG + TVDRK2.

Generates a log-log plot of element size h vs. L2 error with O(h^2)
reference line and best-fit slope annotation.

Usage:
    python plot_convergence.py                        # custom kernel results
    python plot_convergence.py --compare              # custom + built-in on one plot
    python plot_convergence.py --clean                # only built-in baseline
    python plot_convergence.py -o mms_paper.pdf       # save as PDF for journal
"""

import sys
import csv
from pathlib import Path
import argparse

import numpy as np
import matplotlib
matplotlib.rcParams.update({
    "font.family":     "serif",
    "font.size":       11,
    "axes.labelsize":  12,
    "axes.titlesize":  12,
    "legend.fontsize": 10,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "figure.dpi":      150,
    "savefig.dpi":     300,
    "savefig.bbox":    "tight",
})
import matplotlib.pyplot as plt

SCRIPT_DIR = Path(__file__).resolve().parent


# ── Data loading ───────────────────────────────────────────────────────────

def load_from_csvs(nx_list=(50, 100, 200, 400), prefix="mms_out"):
    """Read L2 error from CSV files generated by run_mms.py."""
    h_vals, err_vals = [], []
    for nx in nx_list:
        csv_path = SCRIPT_DIR / f"{prefix}_n{nx}.csv"
        if not csv_path.exists():
            print(f"WARNING: {csv_path} not found, skipping nx={nx}")
            continue
        with open(csv_path, "r") as f:
            rows = list(csv.DictReader(f))
        if not rows:
            continue
        err = float(rows[-1]["l2_error"])
        h = 1.0 / nx
        h_vals.append(h)
        err_vals.append(err)
        print(f"  nx={nx}: h={h:.6f}, L2_error={err:.6e}")
    return np.array(h_vals), np.array(err_vals)


# ── Plotting ───────────────────────────────────────────────────────────────

def plot_convergence(h, err, label=None, ax=None, color="k", marker="o"):
    """Plot convergence data on the given axes. Returns fitted slope."""
    log_h, log_err = np.log(h), np.log(err)
    slope, intercept = np.polyfit(log_h, log_err, 1)

    if ax is None:
        _, ax = plt.subplots(figsize=(5.5, 4.5))

    lbl = label or "DG + TVDRK2"

    # Data points
    ax.loglog(h, err, marker=marker, color=color, linestyle="None",
              markersize=8, markerfacecolor="None", markeredgewidth=1.5,
              label=lbl, zorder=5)

    # Best-fit line (dashed)
    ax.loglog(h, np.exp(intercept) * h ** slope,
              color=color, linestyle="--", linewidth=1.0, alpha=0.7,
              label=f"{lbl}  (slope = {slope:.2f})")

    # O(h^2) reference
    ref_h = np.array([h[0] * 1.3, h[-1] * 0.7])
    ref_err = err[-1] * (ref_h / h[-1]) ** 2
    ax.loglog(ref_h, ref_err, color="gray", linestyle="dotted", linewidth=1.0,
              label=r"$\mathcal{O}(h^2)$ reference")

    return slope


def make_plot(h_custom, err_custom, h_baseline=None, err_baseline=None,
              out_path=None):
    """Create publication-quality MMS convergence figure."""
    fig, ax = plt.subplots(figsize=(5.5, 4.5))

    # Plot custom kernel results first
    slope_custom = plot_convergence(h_custom, err_custom,
                                     label="DG + TVDRK2", ax=ax,
                                     color="k", marker="o")

    # Optionally overlay built-in baseline
    if h_baseline is not None and err_baseline is not None and len(h_baseline) > 0:
        plot_convergence(h_baseline, err_baseline,
                          label="Built-in kernels", ax=ax,
                          color="0.4", marker="s")

    # Axis labels
    ax.set_xlabel(r"Element size  $h$")
    ax.set_ylabel(r"$L_2$ error  $\|\rho_h - \rho_{\rm exact}\|_{L_2(\Omega)}$")

    # Legend with consistent ordering
    handles, labels = ax.get_legend_handles_labels()
    # Ensure O(h^2) reference appears last
    handles_reordered = [h for h, l in zip(handles, labels) if "O(h" not in l] + \
                        [h for h, l in zip(handles, labels) if "O(h" in l]
    labels_reordered = [l for l in labels if "O(h" not in l] + \
                       [l for l in labels if "O(h" in l]
    ax.legend(handles_reordered, labels_reordered,
              loc="lower right", frameon=True, fancybox=False,
              edgecolor="0.8")

    # Light grid
    ax.grid(True, which="major", linestyle=":", alpha=0.3)
    ax.grid(True, which="minor", linestyle=":", alpha=0.15)

    fig.tight_layout(pad=0.5)
    out = out_path or str(SCRIPT_DIR / "mms_convergence.pdf")
    fig.savefig(out)
    # Also save a PNG for quick preview
    png_path = Path(out).with_suffix(".png")
    fig.savefig(png_path, dpi=150)
    print(f"\nSaved: {out}")
    print(f"Saved: {png_path}")

    return slope_custom


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Publication-quality MMS convergence plot")
    parser.add_argument("--compare", action="store_true",
                        help="Overlay custom + built-in kernel results")
    parser.add_argument("--clean", action="store_true",
                        help="Plot only built-in baseline results")
    parser.add_argument("--nx", type=int, nargs="+", default=[50, 100, 200, 400],
                        help="Mesh sizes (default: 50 100 200 400)")
    parser.add_argument("-o", "--output", type=str, default=None,
                        help="Output path (.pdf or .png)")
    parser.add_argument("--h", type=float, nargs="+",
                        help="Manual element sizes (overrides CSV loading)")
    parser.add_argument("--err", type=float, nargs="+",
                        help="Manual L2 errors (overrides CSV loading)")
    args = parser.parse_args()

    # Determine output path
    if args.output:
        out_path = args.output
    elif args.clean:
        out_path = str(SCRIPT_DIR / "mms_convergence_baseline.pdf")
    elif args.compare:
        out_path = str(SCRIPT_DIR / "mms_convergence_compare.pdf")
    else:
        out_path = str(SCRIPT_DIR / "mms_convergence.pdf")

    # Manual data entry
    if args.h and args.err:
        if len(args.h) != len(args.err):
            print("Error: --h and --err must have the same number of values")
            sys.exit(1)
        h_custom = np.array(args.h)
        err_custom = np.array(args.err)
        make_plot(h_custom, err_custom, out_path=out_path)
        return

    # Load custom kernel results
    h_custom, err_custom = load_from_csvs(args.nx, prefix="mms_out")

    # Load baseline results if comparing
    h_baseline, err_baseline = None, None
    if args.compare or args.clean:
        h_bl, err_bl = load_from_csvs(args.nx, prefix="mms_clean")
        if args.clean:
            h_custom, err_custom = h_bl, err_bl  # baseline as primary
        else:
            h_baseline, err_baseline = h_bl, err_bl

    if len(h_custom) < 2:
        print("Error: need at least 2 data points. Run run_mms.py first.")
        sys.exit(1)

    slope = make_plot(h_custom, err_custom, h_baseline, err_baseline,
                      out_path=out_path)
    print(f"Best-fit slope: {slope:.3f}")


if __name__ == "__main__":
    main()
